org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
version=26.1.2-2.0.0
group=com.buuz135
java_version=25

# Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
mod_id=darkmodeeverywhere
mod_name=Dark Mode Everywhere
mod_author=Buuz135
license=MIT
credits=
description=Dark Mode GUIs Everywhere
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.153.0+26.1.2
fabric_loader_version=0.19.3
fabric_minecraft_version_range=>=26.1.2 <26.2

# NeoForge
neoforge_version=26.1.2.76
neoforge_loader_version_range=[4,)
