org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
version=1.21.1-1.4.0
group=com.buuz135
java_version=21

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
mod_id=darkmodeeverywhere
mod_name=Dark Mode Everywhere
mod_author=Buuz135
license=MIT
credits=
description=Dark Mode GUIs Everywhere
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.15.11
fabric_minecraft_version_range=>=1.21.1 <1.21.2

# NeoForge
neoforge_version=21.1.50
neoforge_loader_version_range=[4,)
