name: Publish action

on:
  create:
    tag:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 21
        uses: actions/setup-java@v1
        with:
          java-version: "21"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Forge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 574123
          modrinth-id: R6YQjhwo
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar
          version-type: beta
          loaders: neoforge
          game-versions: 1.21
          java: 21
          name: ""
          changelog: "https://github.com/Buuz135/DarkModeEverywhere/commits/1.21"
